---
- name: Vector | Download packages
  ansible.builtin.get_url:
#    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    url: "{{ vector_url }}"
    dest: "/home/ansible/vector-{{ vector_version }}-1.x86_64.rpm"
#    mode: '0755'
- name: Vector | Install packages
  become: true
  ansible.builtin.yum:
    name: "/home/ansible/vector-{{ vector_version }}-1.x86_64.rpm"
    state: present
    disable_gpg_check: true
- name: Vector | Apply template
  become: true
  ansible.builtin.template:
    src: vector.yml.j2
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: '0644'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
- name: Vector | Change systemd unit
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: true
  notify: Start vector service
